# Generated by Django 4.0.6 on 2023-03-12 23:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import klient.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('nip', models.CharField(max_length=10, validators=[klient.models.only_int, django.core.validators.MinLengthValidator(10)])),
                ('adres', models.CharField(max_length=100)),
                ('miejscowosc', models.CharField(max_length=30)),
                ('wojewodztwo', models.CharField(max_length=30)),
                ('telefon', models.CharField(max_length=9, validators=[klient.models.only_int, django.core.validators.MinLengthValidator(9)])),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
